FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8000

# Update this to include Uvicorn configuration for large uploads
CMD ["uvicorn", "app.main:app","--workers", "1", "--host", "0.0.0.0", "--port", "8000", "--timeout-keep-alive", "600"]